const today = RijiCloud.now();
const isoToday = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const colors = {睡眠:'#3974a8',学习:'#1d6b4b',生活:'#e3a72f',娱乐:'#c84c43',未记录:'#dfe4df'};
const natureColors={sleep:'#8b6fd6',positive:'#e8d9a8',neutral:'#d8dcd8'};
const initialRecords = [
  {id:1,date:isoToday,start:'00:00',end:'06:50',name:'睡眠',category:'睡眠',path:'家 / 卧室 / 床'},
  {id:2,date:isoToday,start:'07:10',end:'07:40',name:'洗漱与早餐',category:'生活',path:'家 / 卫生间'},
  {id:3,date:isoToday,start:'09:00',end:'10:20',name:'预习概率论',category:'学习',path:'家 / 卧室 / 书桌'},
  {id:4,date:isoToday,start:'14:15',end:'15:05',name:'阅读',category:'学习',path:'家 / 客厅'},
  {id:5,date:isoToday,start:'20:10',end:'20:40',name:'散步',category:'生活',path:'小区'},
];
let state = RijiData.load({region:'上海',sleeping:false,sleepStart:null,activeTimer:null,records:initialRecords});
const demoIds=new Set([1,2,3,4,5]),futureDemoIds=state.records.filter(record=>demoIds.has(record.id)&&RijiData.validateTimeWindow(record.date,record.start,record.end,RijiCloud.now())).map(record=>record.id);state.records=state.records.filter(record=>!futureDemoIds.includes(record.id));state.deletedRecordIds=[...new Set([...(state.deletedRecordIds||[]),...futureDemoIds])];
let selectedAction = null, timerTicker = null, activeMode = 'timer', editingSceneKey = 'desk', editingAction = null, editingRecordId = null, distributionMode = 'recorded', regionEditMode = null;
const scenes = {
  '上海': {title:'书桌',path:'上海 / 家 / 卧室 / 书桌',copy:'窗外的城市还没有安静下来。桌面已经收拾好，现在准备做什么？',options:[['预习概率论','学习 · 可计时','学习'],['阅读一会儿','学习 · 可计时','学习'],['休息一下','留在当前场景 · 循环','娱乐'],['离开书桌','前往卧室','生活'],['准备入眠','前往床 · 睡眠','睡眠']]},
  '杭州': {title:'窗边',path:'杭州 / 住处 / 客厅 / 窗边',copy:'雨刚停，窗沿还留着水珠。给自己留一点安静的时间。',options:[['阅读','学习 · 可计时','学习'],['泡一杯茶','生活 · 前往厨房','生活'],['整理今天的记录','生活 · 留在当前场景','生活']]}
};
Object.assign(scenes,state.customScenes||{});
const sceneMaps={
  '上海':{
    home:{title:'家',icon:'home',path:'上海 / 家',copy:'回到熟悉的空间。这里通往卧室、浴室和客厅。',options:[
      {name:'前往卧室',hint:'通往卧室 · 不计时',kind:'navigate',target:'bedroom'},
      {name:'前往浴室',hint:'通往浴室 · 不计时',kind:'navigate',target:'bathroom'},
      {name:'前往客厅',hint:'通往客厅 · 不计时',kind:'navigate',target:'livingroom'}]},
    desk:{title:'书桌',icon:'desk',path:'上海 / 家 / 卧室 / 书桌',copy:'窗外的城市还没有安静下来。桌面已经收拾好，现在准备做什么？',options:[
      {name:'预习概率论',hint:'学习 · 可计时',kind:'学习'},
      {name:'阅读一会儿',hint:'学习 · 可计时',kind:'学习'},
      {name:'休息一下',hint:'娱乐 · 可计时',kind:'娱乐'},
      {name:'离开书桌',hint:'通往卧室 · 不计时',kind:'navigate',target:'bedroom'}]},
    bedroom:{title:'卧室',icon:'bed',path:'上海 / 家 / 卧室',copy:'卧室里很安静。书桌、床和门分别通向不同的生活片段。',options:[
      {name:'走到书桌',hint:'通往书桌 · 不计时',kind:'navigate',target:'desk'},
      {name:'前往浴室',hint:'通往浴室 · 不计时',kind:'navigate',target:'bathroom'},
      {name:'走到床边',hint:'通往床 · 不计时',kind:'navigate',target:'bed'}]},
    bed:{title:'床',icon:'bed',path:'上海 / 家 / 卧室 / 床',copy:'床铺已经整理好。你可以在这里休息、阅读，也可以选择正式入眠。',options:[
      {name:'入眠',hint:'开始睡眠记录',kind:'睡眠'},
      {name:'躺着休息',hint:'生活 · 可计时',kind:'生活'},
      {name:'床上阅读',hint:'学习 · 可计时',kind:'学习'},
      {name:'返回卧室',hint:'通往卧室 · 不计时',kind:'navigate',target:'bedroom'}]},
    bathroom:{title:'浴室',icon:'bath',path:'上海 / 家 / 浴室',copy:'镜面映着柔和的灯光。可以在这里完成洗漱，也可以随时返回卧室。',options:[
      {name:'洗漱',hint:'生活 · 可计时',kind:'生活'},
      {name:'洗澡',hint:'生活 · 可计时',kind:'生活'},
      {name:'返回卧室',hint:'通往卧室 · 不计时',kind:'navigate',target:'bedroom'},
      {name:'返回家中',hint:'通往家 · 不计时',kind:'navigate',target:'home'}]},
    livingroom:{title:'客厅',icon:'sofa',path:'上海 / 家 / 客厅',copy:'客厅连接着家里的公共空间，适合阅读、放松，或去往其他房间。',options:[
      {name:'沙发阅读',hint:'学习 · 可计时',kind:'学习'},
      {name:'放松一会儿',hint:'娱乐 · 可计时',kind:'娱乐'},
      {name:'返回家中',hint:'通往家 · 不计时',kind:'navigate',target:'home'}]}
  }
};
if(state.sceneMaps)Object.entries(state.sceneMaps).forEach(([region,map])=>{sceneMaps[region]=region==='上海'?{...sceneMaps.上海,...map}:map});
const legacyShanghaiTree=state.sceneTrees?.上海||state.sceneTree||{home:{parent:null,children:['bedroom','bathroom','livingroom']},bedroom:{parent:'home',children:['bed','desk']},bed:{parent:'bedroom',children:[]},desk:{parent:'bedroom',children:[]},bathroom:{parent:'home',children:[]},livingroom:{parent:'home',children:[]}};
let sceneTrees={...(state.sceneTrees||{}),上海:legacyShanghaiTree};
let sceneTree=sceneTrees.上海;
if(!sceneMaps.上海.region)sceneMaps.上海.region={title:'上海',icon:'pin',path:'上海',copy:'选择要前往的生活区域。',options:[]};
if(!sceneMaps.上海.outdoor)sceneMaps.上海.outdoor={title:'户外',icon:'pin',path:'上海 / 户外',copy:'已经来到户外。可以继续前往小区、公园或其他地点。',options:[{name:'散步',hint:'中性活动 · 可计时',kind:'生活',tag:'散步',timeNature:'neutral',recordMode:'internal'}]};
if(!sceneTree.region){sceneTree.region={parent:null,children:['home','outdoor']};sceneTree.home.parent='region';sceneTree.outdoor={parent:'region',children:[]}}
if(!sceneMaps.上海.home.options.some(option=>option.target==='outdoor'))sceneMaps.上海.home.options.push({name:'出门',hint:'通往户外 · 不计时',kind:'navigate',target:'outdoor',timeNature:'passage',recordMode:'none',tag:''});
if(!sceneMaps.上海.outdoor.options.some(option=>option.target==='home'))sceneMaps.上海.outdoor.options.push({name:'回家',hint:'通往家 · 不计时',kind:'navigate',target:'home',timeNature:'passage',recordMode:'none',tag:''});
function createRegionData(name){return {map:{region:{title:name,icon:'pin',path:name,copy:'选择要前往的生活区域。',options:[]},home:{title:'家',icon:'home',path:`${name} / 家`,copy:'这是该地区的家。可以继续创建卧室、客厅或其他子场景。',options:[]}},tree:{region:{parent:null,children:['home']},home:{parent:'region',children:[]}}}}
Object.keys(scenes).forEach(name=>{if(!sceneMaps[name]){const created=createRegionData(name);sceneMaps[name]=created.map;sceneTrees[name]=created.tree}else if(!sceneTrees[name])sceneTrees[name]=createRegionData(name).tree});
state.archivedRegions=state.archivedRegions||[];
const rememberedRegions=new Set([state.region,...(state.regions||[]),...Object.keys(state.customScenes||{}),...(state.records||[]).map(record=>record.region).filter(Boolean)]);
rememberedRegions.forEach(name=>{if(!sceneMaps[name]){const created=createRegionData(name);sceneMaps[name]=created.map;sceneTrees[name]=created.tree}});
sceneTree=sceneTrees[state.region]||sceneTrees.上海;
const defaultIcons={home:'home',bedroom:'bed',bed:'bed',desk:'desk',bathroom:'bath',livingroom:'sofa'};
Object.values(sceneMaps).forEach(map=>Object.entries(map).forEach(([key,scene])=>{scene.icon=scene.icon||defaultIcons[key]||'pin';(scene.options||[]).forEach(option=>{if(Array.isArray(option))return;option.tag=option.tag||((option.kind==='navigate'||option.kind==='睡眠')?'':option.kind);option.timeNature=option.timeNature||(option.kind==='睡眠'?'sleep':option.kind==='navigate'?'passage':option.kind==='娱乐'?'neutral':'positive');option.recordMode=option.recordMode||(option.timeNature==='positive'?'external':option.timeNature==='passage'||option.timeNature==='sleep'?'none':'internal')})}));
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
function activeMap(){return sceneMaps[state.region]}
function activeRegionNames(){const archived=new Set(state.archivedRegions||[]);return Object.keys(sceneMaps).filter(name=>!archived.has(name))}
function save(sceneChanged=false,timerChanged=false){sceneTrees[state.region]=sceneTree;state.sceneMaps=sceneMaps;state.sceneTrees=sceneTrees;state.sceneTree=sceneTrees.上海;state.regions=activeRegionNames();state.sync=state.sync||{};if(sceneChanged){state.sync.sceneRevision=(state.sync.sceneRevision||0)+1;state.sync.sceneConflict=null}if(timerChanged){state.sync.timerRevision=(state.sync.timerRevision||0)+1;state.sync.timerConflict=null}RijiData.save(state);RijiCloud.schedule(()=>state,()=>location.reload());}
function toast(msg){const el=$('#toast'),openDialogs=$$('dialog[open]'),host=openDialogs.at(-1)||document.body;if(el.parentElement!==host)host.appendChild(el);el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function minutes(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function duration(a,b){const diff=minutes(b)-minutes(a);return diff>=0?diff:diff+1440}
function fmtMin(m){return m>=60?`${Math.floor(m/60)}小时${m%60?` ${m%60}分`:''}`:`${m}分钟`}
function clockNow(){return RijiCloud.now()}function clockOffset(){return RijiCloud.clock().offsetMs||0}function dateKey(date=clockNow()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}function nowTime(){return clockNow().toTimeString().slice(0,5)}
function iconSvg(key,className='scene-icon'){const icon=activeMap()?.[key]?.icon||scenes[state.region]?.icon||'pin';return `<svg class="${className}" aria-hidden="true"><use href="#i-${icon}"></use></svg>`}
function recordIconSvg(record,className='flow-icon'){const map=sceneMaps[record.region]||activeMap(),icon=map?.[record.sceneKey]?.icon||'pin';return `<svg class="${className}" aria-hidden="true"><use href="#i-${icon}"></use></svg>`}
function recordNature(record){return record.timeNature||(record.category==='睡眠'?'sleep':record.category==='娱乐'?'neutral':'positive')}
function recordSceneKey(record){if(record.sceneKey&&activeMap()?.[record.sceneKey])return record.sceneKey;if(record.path?.includes('浴室')||record.path?.includes('卫生间'))return'bathroom';if(record.path?.includes('书桌'))return'desk';if(record.path?.includes('床'))return'bed';if(record.path?.includes('客厅'))return'livingroom';return'home'}
function nav(page){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.remove('active'));$(`#${page}Page`).classList.add('active');if(page==='timeline')renderTimeline();}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
function structuralOptions(sceneKey){if(!sceneTree[sceneKey])return[];const map=activeMap(),links=[],parent=sceneTree[sceneKey].parent;if(parent)links.push({name:`返回${map[parent].title}`,kind:'navigate',target:parent,timeNature:'passage',structural:true});sceneTree[sceneKey].children.forEach(child=>links.push({name:`前往${map[child].title}`,kind:'navigate',target:child,timeNature:'passage',structural:true}));return links}
function renderScene(){
  const fallback=scenes[state.region],map=activeMap(),defaultKey=map.desk?'desk':'home',sceneKey=state.currentScenes?.[state.region]||defaultKey;
  const s=map?.[sceneKey]||fallback,currentPath=map?.[sceneKey]?scenePath(sceneKey):s.path;$('#sceneTitle').textContent=state.sleeping?'睡眠中':s.title;$('#scenePath').textContent=state.sleeping?`${state.region} / 家 / 卧室 / 床`:currentPath;$('#sceneCopy').textContent=state.sleeping?`从 ${state.sleepStart} 开始睡眠。夜间如需活动，请先结束当前睡眠段。`:s.copy;
  const own=(s.options||[]).map(o=>Array.isArray(o)?{name:o[0],hint:o[1],kind:o[2]}:o),existingTargets=new Set(own.filter(o=>o.kind==='navigate').map(o=>o.target)),autoLinks=structuralOptions(sceneKey).filter(o=>!existingTargets.has(o.target));
  const opts=state.sleeping?[{name:'起床',hint:'结束睡眠并填写质量评分',kind:'wake'},{name:'夜间活动',hint:'切断当前睡眠段，恢复活动选择',kind:'night'}]:[...own,...autoLinks];
  $('#optionList').innerHTML=opts.map((o,i)=>`<button class="scene-option ${o.kind==='睡眠'?'sleep':''}" data-index="${i}" data-action="${o.name}" data-kind="${o.kind}" data-target="${o.target||''}">${iconSvg(state.sleeping?'bed':sceneKey)}<div><strong>${o.name}</strong></div><span class="arrow">›</span></button>`).join('');
  $$('.scene-option').forEach(b=>bindSceneOption(b,sceneKey,opts));renderStatus();
}
function bindSceneOption(button,sceneKey,opts){let holdTimer,longPressed=false,editable=!state.sleeping&&Boolean(sceneMaps[state.region]?.[sceneKey]);button.onpointerdown=()=>{longPressed=false;if(editable)holdTimer=setTimeout(()=>{longPressed=true;openActionEditor(sceneKey,Number(button.dataset.index))},520)};button.onpointerup=()=>clearTimeout(holdTimer);button.onpointerleave=()=>clearTimeout(holdTimer);button.oncontextmenu=e=>{if(!editable)return;e.preventDefault();clearTimeout(holdTimer);openActionEditor(sceneKey,Number(button.dataset.index))};button.onkeydown=e=>{if(editable&&e.key==='Enter'&&e.shiftKey){e.preventDefault();openActionEditor(sceneKey,Number(button.dataset.index))}};button.onclick=e=>{if(longPressed){e.preventDefault();return}const action=opts[Number(button.dataset.index)];handleOption(action.name,action.kind,action.target,action)}}
function switchRegion(){
  const name=$('#regionSelect').value.trim();
  if(!name)return toast('请输入地区名称');
  if(state.archivedRegions.includes(name))return toast('该地区已归档，请先在场景管理中恢复');
  const isNew=!sceneMaps[name];
  if(isNew){const created=createRegionData(name);sceneMaps[name]=created.map;sceneTrees[name]=created.tree;scenes[name]=created.map.home;state.customScenes={...(state.customScenes||{}),[name]:scenes[name]}}
  state.region=name;sceneTree=sceneTrees[name];state.currentScenes={...(state.currentScenes||{}),[name]:state.currentScenes?.[name]||'home'};editingSceneKey=state.currentScenes[name];save(isNew);renderRegionOptions();closeRegionOptions();renderScene();openSceneEditor(editingSceneKey);renderTimeline();renderDistribution();toast(isNew?`已创建地区：${name}`:`已切换到${name}`);
}
function regionNames(){return activeRegionNames().sort((a,b)=>a.localeCompare(b,'zh-CN'))}
function renderRegionOptions(){const names=regionNames();$('#regionOptions').innerHTML=names.map(name=>`<button type="button" role="option" aria-selected="${name===state.region}" data-region="${name}">${name}<small>${name===state.region?'当前地区':'切换'}</small></button>`).join('');$$('#regionOptions [data-region]').forEach(button=>button.onclick=()=>{$('#regionSelect').value=button.dataset.region;switchRegion()})}
function openRegionOptions(){renderRegionOptions();$('#regionOptions').classList.remove('hidden');$('#regionSelect').setAttribute('aria-expanded','true');$('#regionToggle').setAttribute('aria-expanded','true')}
function closeRegionOptions(){$('#regionOptions').classList.add('hidden');$('#regionSelect').setAttribute('aria-expanded','false');$('#regionToggle').setAttribute('aria-expanded','false')}
function toggleRegionOptions(){if($('#regionOptions').classList.contains('hidden'))openRegionOptions();else closeRegionOptions()}
function handleOption(name,kind,target,action){if(kind==='navigate')return navigateScene(target);if(kind==='睡眠'){if(state.activeTimer)return toast('请先结束当前计时再入眠');return openSleep('sleep')}if(kind==='wake')return openSleep('wake');if(kind==='night'){endSleep(false);toast('睡眠段已切断，可以记录夜间活动');return}const chosen=action||{name,kind};if(chosen.recordMode==='external'||chosen.timeNature==='positive')return openSyncDialog(chosen);if(state.activeTimer)return toast('已有行动正在计时，请先结束后再开始新的行动');openAction(chosen)}
function syncActionRuleFields(){const nature=$('#editActionNature').value,mode=$('#editActionRecordMode');$('#editActionTag').disabled=nature==='sleep'||nature==='passage';$('#editActionTarget').disabled=nature==='sleep';mode.disabled=nature==='sleep'||nature==='passage';if(nature==='positive')mode.value='external';if(nature==='sleep'||nature==='passage'){mode.value='none';$('#editActionTag').value=''}}
function openActionEditor(sceneKey,index){const map=activeMap(),scene=map[sceneKey],action=scene.options[index];if(!action||Array.isArray(action))return;editingAction={sceneKey,index};$('#editActionHeading').textContent=action.name;$('#editActionName').value=action.name;$('#editActionTag').value=action.tag||'';$('#editActionNature').value=action.timeNature||(action.kind==='睡眠'?'sleep':action.kind==='navigate'?'passage':'positive');$('#editActionRecordMode').value=action.recordMode||(action.timeNature==='positive'?'external':'internal');$('#editActionTarget').innerHTML=`<option value="">不跳转</option>${allSceneKeys().filter(key=>key!==sceneKey).map(key=>`<option value="${key}" ${action.target===key?'selected':''}>前往${map[key].title}</option>`).join('')}`;syncActionRuleFields();$('#actionEditDialog').showModal()}
$('#editActionNature').onchange=syncActionRuleFields;
$('#saveActionEdit').onclick=()=>{if(!editingAction)return;const map=activeMap(),{sceneKey,index}=editingAction,action=map[sceneKey].options[index],name=$('#editActionName').value.trim()||action.name,tag=$('#editActionTag').value.trim(),nature=$('#editActionNature').value,target=$('#editActionTarget').value,recordMode=$('#editActionRecordMode').value;action.name=name;action.tag=tag;if(nature==='sleep'){action.kind='睡眠';action.timeNature='sleep';action.recordMode='none';delete action.target;action.hint='开始睡眠记录'}else if(target||nature==='passage'){if(!target)return toast('场景通道需要选择目标场景');action.kind='navigate';action.timeNature='passage';action.recordMode='none';action.tag='';action.target=target;action.hint=`通往${map[target].title} · 不计时`}else{action.kind=action.kind==='navigate'||action.kind==='睡眠'?'生活':action.kind;action.timeNature=nature;action.recordMode=nature==='positive'?'external':recordMode;delete action.target;action.hint=`${tag||action.kind} · 可计时`}save(true);$('#actionEditDialog').close();renderScene();if(editingSceneKey===sceneKey)renderActions();toast('行动修改已保存')};
$('#deleteAction').onclick=()=>{if(!editingAction)return;const {sceneKey,index}=editingAction;activeMap()[sceneKey].options.splice(index,1);save(true);$('#actionEditDialog').close();renderScene();if(editingSceneKey===sceneKey)renderActions();toast('行动已删除')};
function navigateScene(target){state.currentScenes={...(state.currentScenes||{}),[state.region]:target};save();renderScene();toast(`已前往${activeMap()[target].title}`)}
function openAction(action){selectedAction={...action,sceneKey:state.currentScenes?.[state.region]||'desk'};$('#dialogActionName').textContent=action.name;activeMode='timer';renderMode();$('#actionDialog').showModal()}
function mindfulCatalog(){const items=[];Object.entries(activeMap()).forEach(([sceneKey,scene])=>(scene.options||[]).forEach((action,index)=>{if(!Array.isArray(action)&&action.timeNature==='positive'&&action.kind!=='navigate')items.push({sceneKey,index,action})}));return items}
function addSyncRow(prefill){const map=activeMap(),catalog=mindfulCatalog(),row=document.createElement('div');row.className='sync-row';row.innerHTML=`<select class="sync-action">${catalog.map(item=>`<option value="${item.sceneKey}|${item.index}" ${prefill?.name===item.action.name?'selected':''}>${map[item.sceneKey].title} · ${item.action.name}</option>`).join('')}</select><input class="sync-start" type="time" value="09:00"><input class="sync-end" type="time" value="10:00"><button type="button" aria-label="删除">×</button>`;row.querySelector('button').onclick=()=>row.remove();$('#syncRows').append(row)}
function openSyncDialog(prefill){$('#syncDate').value=dateKey();$('#syncRows').innerHTML='';addSyncRow(prefill);$('#syncDialog').showModal()}
$('#addSyncRow').onclick=()=>addSyncRow();
$('#saveSync').onclick=()=>{const map=activeMap(),date=$('#syncDate').value,source=$('#syncSource').value.trim()||'其他软件',pending=[];for(const row of $$('.sync-row')){const [sceneKey,index]=row.querySelector('.sync-action').value.split('|'),start=row.querySelector('.sync-start').value,end=row.querySelector('.sync-end').value,action=map[sceneKey].options[Number(index)],timeError=RijiData.validateTimeWindow(date,start,end,clockNow());if(timeError)return toast(timeError);pending.push({sceneKey,action,start,end})}const existing=state.records.filter(r=>r.date===date&&r.region===state.region);for(const item of pending){const a1=minutes(item.start),a2=a1+duration(item.start,item.end);const conflict=[...existing,...pending.filter(x=>x!==item).map(x=>({start:x.start,end:x.end,name:x.action.name}))].find(r=>{const b1=minutes(r.start),b2=b1+duration(r.start,r.end);return a1<b2&&b1<a2});if(conflict)return toast(`时间与“${conflict.name}”重叠，请调整后再保存`);if(existing.some(r=>r.name===item.action.name&&r.start===item.start&&r.end===item.end))return toast('发现疑似重复记录，未保存')}pending.forEach(item=>state.records.push({id:Date.now()+Math.random(),date,start:item.start,end:item.end,name:item.action.name,category:item.action.kind,timeNature:'positive',tag:item.action.tag||'',recordMode:'external',source,region:state.region,sceneKey:item.sceneKey,path:scenePath(item.sceneKey).replace(`${state.region} / `,'')}));save();renderTimeline();renderDistribution();$('#syncDialog').close();toast(`已同步 ${pending.length} 条正念记录`)};
function renderMode(){ $$('.mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===activeMode));const panel=$('#modePanel');if(activeMode==='manual')panel.innerHTML=`<label>投入时长（分钟）<input id="manualMinutes" type="number" min="1" value="30"></label>`;else if(activeMode==='pomodoro')panel.innerHTML=`<label>番茄钟时长（分钟）<input id="pomoMinutes" type="number" min="5" value="25"></label><div class="timer-preview">25:00</div>`;else panel.innerHTML='<div class="timer-preview">从现在开始</div>';$('#confirmAction').textContent=activeMode==='manual'?'添加记录':'开始计时'}
$$('.mode-tabs button').forEach(b=>b.onclick=()=>{activeMode=b.dataset.mode;renderMode()});
$('#confirmAction').onclick=()=>{if(activeMode==='manual'){const m=Number($('#manualMinutes').value)||30;const end=nowTime(), startMin=Math.max(0,minutes(end)-m);addRecord(selectedAction.name,selectedAction.kind,`${String(Math.floor(startMin/60)).padStart(2,'0')}:${String(startMin%60).padStart(2,'0')}`,end,selectedAction.timeNature,selectedAction.tag,selectedAction.sceneKey);toast('时间记录已添加')}else{const startedAt=Date.now(),sceneKey=selectedAction.sceneKey,path=scenePath(sceneKey);state.activeTimer={name:selectedAction.name,kind:selectedAction.kind,timeNature:selectedAction.timeNature,tag:selectedAction.tag,sceneKey,region:state.region,path,start:startedAt,startedAt,segments:[{start:startedAt,end:null}],paused:false,sessionId:`timer_${startedAt}`,pomodoro:activeMode==='pomodoro'?Number($('#pomoMinutes').value):null};if(activeMode==='pomodoro'&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});save(false,true);renderStatus();toast('计时已开始')}$('#actionDialog').close()};
function addRecord(name,category,start,end,timeNature,tag,forcedSceneKey,date=null,details={}){const map=activeMap(),key=forcedSceneKey||state.currentScenes?.[state.region]||(map.desk?'desk':'home'),current=map[key]||scenes[state.region],path=map[key]?scenePath(key):current.path;state.records.push({id:Date.now()+Math.random(),date:date||dateKey(),start,end,name,category,timeNature:timeNature||(category==='睡眠'?'sleep':category==='娱乐'?'neutral':'positive'),tag:tag||category,region:state.region,sceneKey:key,path:path.replace(`${state.region} / `,''),...details});save();renderStatus();renderTimeline();renderDistribution()}
function addTimestampRecords(name,category,startAt,endAt,timeNature,tag,sceneKey,details={}){const parts=RijiData.splitTimeWindow(startAt,endAt);parts.forEach(part=>addRecord(name,category,part.start,part.end,timeNature,tag,sceneKey,part.date,{...details,...(details.idPrefix||details.sessionId?{id:`${details.idPrefix||details.sessionId}_${part.date}`}:{})}));return parts.length}
function timerElapsed(timer,now=Date.now()){return (timer.segments||[]).reduce((total,segment)=>total+Math.max(0,(segment.end||now)-segment.start),0)}
function timerText(ms){const sec=Math.floor(ms/1000);return[Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(n=>String(n).padStart(2,'0')).join(':')}
function closeTimerSegment(timer,at=Date.now()){const segment=timer.segments?.at(-1);if(segment&&!segment.end)segment.end=at}
function recordTimer(timer,endAt=Date.now()){closeTimerSegment(timer,endAt);const offset=clockOffset();let count=0;(timer.segments||[]).forEach((segment,index)=>{if(segment.end>segment.start)count+=addTimestampRecords(timer.name,timer.kind,segment.start+offset,segment.end+offset,timer.timeNature,timer.tag,timer.sceneKey,{sessionId:timer.sessionId,idPrefix:`${timer.sessionId}_${index}`,region:timer.region,path:timer.path})});return count}
function finishTimer(message='已结束并写入时间账本'){const timer=state.activeTimer;if(!timer)return;recordTimer(timer);state.activeTimer=null;save(false,true);clearInterval(timerTicker);renderStatus();toast(message)}
function pauseActiveTimer(auto=false){const timer=state.activeTimer;if(!timer||timer.paused)return;closeTimerSegment(timer);timer.paused=true;timer.pausedAt=Date.now();save(false,true);renderStatus();if(!auto)toast('计时已暂停')}
function resumeActiveTimer(){const timer=state.activeTimer;if(!timer||!timer.paused)return;timer.paused=false;timer.pausedAt=null;timer.pomodoroReached=false;timer.segments.push({start:Date.now(),end:null});save(false,true);renderStatus();toast('计时已继续')}
function pomodoroAlert(){try{const audio=new AudioContext(),oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.connect(gain);gain.connect(audio.destination);gain.gain.value=.08;oscillator.frequency.value=660;oscillator.start();oscillator.stop(audio.currentTime+.35)}catch{}if('Notification'in window&&Notification.permission==='granted')new Notification('日迹番茄钟到时',{body:`${state.activeTimer?.name||'当前行动'}已完成本轮专注`});if(!$('#pomodoroDialog').open)$('#pomodoroDialog').showModal()}
function startTicker(){clearInterval(timerTicker);if(!state.activeTimer)return;const draw=()=>{const timer=state.activeTimer;if(!timer)return;const elapsed=timerElapsed(timer);$('#timerDisplay').textContent=timerText(elapsed);if(timer.pomodoro&&!timer.paused&&!timer.pomodoroReached&&elapsed>=timer.pomodoro*60000){timer.pomodoroReached=true;pauseActiveTimer(true);pomodoroAlert()}};draw();timerTicker=setInterval(draw,1000)}
$('#pauseTimer').onclick=()=>state.activeTimer?.paused?resumeActiveTimer():pauseActiveTimer();$('#stopTimer').onclick=()=>finishTimer();
function dateTimeInputValue(timestamp){const date=new Date(timestamp);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
$('#adjustTimer').onclick=()=>{const timer=state.activeTimer,first=timer?.segments?.[0];if(!first)return toast('当前计时没有可校正的片段');$('#timerStartInput').value=dateTimeInputValue(first.start+clockOffset());$('#timerAdjustDialog').showModal()};
$('#saveTimerStart').onclick=()=>{const timer=state.activeTimer,first=timer?.segments?.[0],wallTime=new Date($('#timerStartInput').value).getTime(),corrected=wallTime-clockOffset();if(!timer||!first||!Number.isFinite(wallTime))return toast('请选择有效的开始时间');if(wallTime>clockNow().getTime())return toast('开始时间不能晚于当前时间');if(first.end&&corrected>=first.end)return toast('开始时间必须早于第一次暂停时间');first.start=corrected;timer.start=corrected;timer.startedAt=corrected;save(false,true);renderStatus();$('#timerAdjustDialog').close();toast('计时开始时间已校正')};
function openTimerDecision(abnormal=false){$('#timerCancelHeading').textContent=abnormal?'检测到异常长的计时':'取消当前计时？';$('#timerCancelText').textContent=abnormal?'该会话已经持续超过 18 小时，请确认保存有效投入时间、放弃会话，或关闭窗口后继续计时。':'可以保存已经投入的有效时间，也可以放弃整次会话。';if(!$('#timerCancelDialog').open)$('#timerCancelDialog').showModal()}
$('#cancelTimer').onclick=()=>openTimerDecision();$('#discardTimer').onclick=()=>{state.activeTimer=null;save(false,true);renderStatus();$('#timerCancelDialog').close();toast('本次计时已放弃')};$('#saveCancelledTimer').onclick=()=>{finishTimer('已保存取消前的投入时间');$('#timerCancelDialog').close()};
$('#continuePomodoro').onclick=()=>{resumeActiveTimer();$('#pomodoroDialog').close()};$('#finishPomodoro').onclick=()=>{finishTimer('番茄钟已完成并记录');$('#pomodoroDialog').close()};
function openSleep(mode){const wake=mode==='wake',qualityInput=$('#sleepQuality');$('#sleepDialogTitle').textContent=wake?'准备起床':'准备入眠';$('#sleepDialogText').textContent=wake?`本次从 ${state.sleepStart} 开始，确认后将恢复其他活动。`:'入眠后将进入睡眠状态，起床前只能选择“起床”或“夜间活动”。';$('#sleepQualityWrap').classList.toggle('hidden',!wake);if(wake)qualityInput.value='';$('#confirmSleep').textContent=wake?'确认起床':'确认入眠';$('#confirmSleep').onclick=()=>{if(wake&&!qualityInput.checkValidity())return toast('睡眠质量应为 0 到 100');wake?endSleep(true):beginSleep();$('#sleepDialog').close()};$('#sleepDialog').showModal()}
function beginSleep(){state.sleeping=true;state.sleepStartedAt=new Date().toISOString();state.sleepStart=nowTime();save();renderScene();toast('已进入睡眠状态')}
function endSleep(waking){const quality=waking&&$('#sleepQuality').value!==''?Number($('#sleepQuality').value):null,startAt=state.sleepStartedAt,sessionId=startAt?`sleep_${startAt}`:null,offset=clockOffset();if(startAt)addTimestampRecords('睡眠','睡眠',Date.parse(startAt)+offset,Date.now()+offset,'sleep','',state.currentScenes?.[state.region],{sleepQuality:quality,sessionId});state.sleeping=false;state.sleepStart=null;state.sleepStartedAt=null;state.lastSleepQuality=quality;save();renderScene();if(waking)toast('早安，睡眠时长和质量已保存')}
function renderStatus(){const timer=state.activeTimer;$('#currentTimer').classList.toggle('hidden',!timer);if(timer){$('#timerName').textContent=timer.name;$('#timerState').textContent=timer.paused?'已暂停':timer.pomodoro?'番茄钟进行中':'正在进行';$('#timerMeta').textContent=`${timer.region||state.region} · ${timer.path||pathForRecord(timer.region||state.region,timer.sceneKey)}`;$('#pauseTimer').textContent=timer.paused?'继续':'暂停';startTicker();if(timer.pomodoroReached&&timer.paused)setTimeout(()=>{if(!$('#pomodoroDialog').open)$('#pomodoroDialog').showModal()},0);const recoveryKey=`riji-long-timer-${timer.sessionId}`;if(!timer.pomodoroReached&&timerElapsed(timer)>18*60*60*1000&&!sessionStorage.getItem(recoveryKey)){sessionStorage.setItem(recoveryKey,'shown');setTimeout(()=>openTimerDecision(true),0)}}else clearInterval(timerTicker)}
function renderTimeline(){
  const date=$('#timelineDate').value||isoToday;
  const recs=state.records.filter(r=>r.date===date&&(!r.region||r.region===state.region)).sort((a,b)=>a.start.localeCompare(b.start));
  const conflicts=RijiData.findRecordOverlaps(state.records).filter(item=>item.region===state.region&&(item.first.date===date||item.second.date===date));$('#timelineConflictSummary').classList.toggle('hidden',!conflicts.length);$('#timelineConflictSummary').textContent=conflicts.length?`这一天存在 ${conflicts.length} 组重叠流水，请在数据管理中处理。`:'';
  const total=recs.reduce((n,r)=>n+duration(r.start,r.end),0),sleep=recs.filter(r=>recordNature(r)==='sleep').reduce((n,r)=>n+duration(r.start,r.end),0);
  $('#timelineSummary').innerHTML=[['已记录',fmtMin(total)],['自然时间占比',`${Math.round(total/1440*100)}%`],['睡眠',fmtMin(sleep)],['未记录',fmtMin(Math.max(0,1440-total))]].map(x=>`<div class="mini-stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  $('#hourLabels').innerHTML=[0,3,6,9,12,15,18,21,24].map(h=>`<span>${String(h).padStart(2,'0')}:00</span>`).join('');
  $('#timeTrack').innerHTML=recs.map(r=>{const visible=Math.min(duration(r.start,r.end),1440-minutes(r.start)),nature=recordNature(r);return `<button class="time-segment" data-record-id="${r.id}" aria-label="编辑${r.name}，${r.start}至${r.end}" title="${r.name} ${r.start}–${r.end}" style="left:${minutes(r.start)/14.4}%;width:${visible/14.4}%;background:${natureColors[nature]||natureColors.neutral}"></button>`}).join('');
  $('#legend').innerHTML=[['睡眠',natureColors.sleep],['正念活动',natureColors.positive],['中性活动',natureColors.neutral]].map(([k,c])=>`<span><i style="background:${c}"></i>${k}</span>`).join('');
  $('#recordsTable').innerHTML=recs.length?recs.map(r=>`<div class="record-row"><span>${r.start}—${r.end}</span><strong>${recordIconSvg(r)}${r.name}</strong><span>${r.path||''}${r.source?` · ${r.source}`:''}${r.sleepQuality!==null&&r.sleepQuality!==undefined?` · 质量 ${r.sleepQuality}`:''}</span><span>${fmtMin(duration(r.start,r.end))}</span><button class="record-edit-button" data-record-id="${r.id}" aria-label="编辑${r.name}" title="编辑记录"><svg aria-hidden="true"><use href="#i-edit"></use></svg></button></div>`).join(''):'<p class="scene-copy">这一天还没有记录。</p>';
  $$('#timeTrack [data-record-id],#recordsTable [data-record-id]').forEach(button=>button.onclick=()=>openRecordEditor(button.dataset.recordId));
}
function renderDistribution(){
  const month=$('#monthSelect').value,records=state.records.filter(r=>r.date.startsWith(month)&&(!r.region||r.region===state.region)&&recordNature(r)!=='sleep'),groups=new Map();
  records.forEach(r=>{const key=`${r.sceneKey||r.path}|${r.name}`,current=groups.get(key)||{name:r.name,minutes:0,record:r};current.minutes+=duration(r.start,r.end);groups.set(key,current)});
  const data=[...groups.values()].sort((a,b)=>b.minutes-a.minutes),recorded=data.reduce((n,item)=>n+item.minutes,0),[year,monthNumber]=month.split('-').map(Number),natural=new Date(year,monthNumber,0).getDate()*1440,denominator=distributionMode==='natural'?natural:recorded;
  $('#distributionBody').innerHTML=data.length?data.map(item=>{const percent=denominator?item.minutes/denominator*100:0;return `<div class="dist-row"><span>${recordIconSvg(item.record)}${item.name}</span><div class="dist-bar"><i style="width:${Math.min(100,percent)}%"></i></div><b>${fmtMin(item.minutes)}</b><small>${percent<1&&percent>0?percent.toFixed(1):Math.round(percent)}%</small></div>`}).join(''):'<p class="scene-copy">本月还没有非睡眠行为记录。</p>';
  renderMonthlySummary(month);renderMonthlyConflicts(month);
}
function renderMonthlyConflicts(month){const conflicts=RijiData.findRecordOverlaps(state.records).filter(item=>item.region===state.region&&(item.first.date.startsWith(month)||item.second.date.startsWith(month)));$('#monthlyConflictSummary').classList.toggle('hidden',!conflicts.length);$('#monthlyConflictSummary').textContent=conflicts.length?`本月存在 ${conflicts.length} 组重叠流水，汇总可能重复计算时间。`:''}
function monthMinutes(month){return state.records.filter(record=>record.date.startsWith(month)&&(!record.region||record.region===state.region)).reduce((total,record)=>total+duration(record.start,record.end),0)}
function renderMonthlySummary(month){const [year,number]=month.split('-').map(Number),days=new Date(year,number,0).getDate(),records=state.records.filter(record=>record.date.startsWith(month)&&(!record.region||record.region===state.region)),total=records.reduce((sum,record)=>sum+duration(record.start,record.end),0),coverage=Math.min(100,Math.round(total/(days*1440)*100)),previousDate=new Date(year,number-2,1),previous=`${previousDate.getFullYear()}-${String(previousDate.getMonth()+1).padStart(2,'0')}`,previousDays=new Date(previousDate.getFullYear(),previousDate.getMonth()+1,0).getDate(),previousCoverage=Math.min(100,Math.round(monthMinutes(previous)/(previousDays*1440)*100)),activeDays=new Set(records.map(record=>record.date)).size,sleepSessions=new Map();records.filter(record=>recordNature(record)==='sleep').forEach(record=>{const key=record.sessionId||record.id,current=sleepSessions.get(key)||{minutes:0,quality:null};current.minutes+=duration(record.start,record.end);if(record.sleepQuality!==null&&record.sleepQuality!==undefined)current.quality=Number(record.sleepQuality);sleepSessions.set(key,current)});const sleeps=[...sleepSessions.values()],averageSleep=sleeps.length?Math.round(sleeps.reduce((sum,item)=>sum+item.minutes,0)/sleeps.length):null,qualities=sleeps.map(item=>item.quality).filter(Number.isFinite),averageQuality=qualities.length?Math.round(qualities.reduce((sum,value)=>sum+value,0)/qualities.length):null;$('#summaryHeading').textContent=`${year}年${number}月的时间账本`;$('#summaryCoverage').textContent=`${coverage}%`;$('#summaryCoverageNote').textContent=`较上月 ${coverage-previousCoverage>=0?'+':''}${coverage-previousCoverage}%`;$('#summaryRecorded').textContent=fmtMin(total);$('#summaryRecordedNote').textContent=`本月 ${activeDays} 天有记录`;$('#summarySleep').textContent=averageSleep===null?'暂无':fmtMin(averageSleep);$('#summarySleepNote').textContent=averageQuality===null?'暂无质量评分':`质量评分 ${averageQuality}`}
function pathForRecord(region,sceneKey){const map=sceneMaps[region],tree=sceneTrees[region];if(!map?.[sceneKey]||!tree?.[sceneKey])return map?.[sceneKey]?.title||'';const names=[];let key=sceneKey;while(key&&map[key]){if(key!=='region')names.unshift(map[key].title);key=tree[key]?.parent}return names.join(' / ')}
function openRecordEditor(id){
  const record=state.records.find(item=>String(item.id)===String(id));if(!record)return;
  editingRecordId=record.id;const region=record.region||state.region,map=sceneMaps[region]||activeMap();
  $('#recordEditDate').value=record.date;$('#recordEditRegion').value=region;$('#recordEditStart').value=record.start;$('#recordEditEnd').value=record.end;$('#recordEditName').value=record.name;$('#recordEditNature').value=recordNature(record);$('#recordEditTag').value=record.tag||'';$('#recordEditSource').value=record.source||'';$('#recordEditQuality').value=record.sleepQuality??'';$('#recordEditQualityWrap').classList.toggle('hidden',recordNature(record)!=='sleep');
  $('#recordEditScene').innerHTML=Object.entries(map).filter(([key])=>key!=='region').map(([key,scene])=>`<option value="${key}" ${key===record.sceneKey?'selected':''}>${scene.title}</option>`).join('');
  $('#deleteRecord').dataset.armed='';$('#deleteRecord').textContent='删除记录';$('#recordEditDialog').showModal();
}
$('#saveRecordEdit').onclick=()=>{const record=state.records.find(item=>String(item.id)===String(editingRecordId));if(!record)return;const date=$('#recordEditDate').value,start=$('#recordEditStart').value,end=$('#recordEditEnd').value,name=$('#recordEditName').value.trim(),sceneKey=$('#recordEditScene').value,timeError=RijiData.validateTimeWindow(date,start,end,clockNow()),qualityInput=$('#recordEditQuality');if(timeError)return toast(timeError);if(!name)return toast('请填写行为名称');if(!qualityInput.checkValidity())return toast('睡眠质量应为 0 到 100');const conflict=state.records.find(item=>String(item.id)!==String(record.id)&&item.date===date&&(item.region||state.region)===(record.region||state.region)&&minutes(start)<minutes(item.start)+duration(item.start,item.end)&&minutes(item.start)<minutes(start)+duration(start,end));if(conflict)return toast(`时间与“${conflict.name}”重叠，请先调整`);record.date=date;record.start=start;record.end=end;record.name=name;record.sceneKey=sceneKey;record.path=pathForRecord(record.region||state.region,sceneKey);record.timeNature=$('#recordEditNature').value;record.tag=$('#recordEditTag').value.trim();record.source=$('#recordEditSource').value.trim();record.sleepQuality=record.timeNature==='sleep'&&qualityInput.value!==''?Number(qualityInput.value):null;record.updatedAt=clockNow().toISOString();save();$('#recordEditDialog').close();renderTimeline();renderDistribution();toast('流水记录已更新')};
$('#deleteRecord').onclick=()=>{const button=$('#deleteRecord');if(!button.dataset.armed){button.dataset.armed='true';button.textContent='再次点击确认删除';toast('再次点击删除按钮以确认');return}state.deletedRecordIds=[...new Set([...(state.deletedRecordIds||[]),editingRecordId])];state.records=state.records.filter(item=>String(item.id)!==String(editingRecordId));save();$('#recordEditDialog').close();renderTimeline();renderDistribution();toast('流水记录已删除')};
$('#recordEditNature').onchange=()=>$('#recordEditQualityWrap').classList.toggle('hidden',$('#recordEditNature').value!=='sleep');
function scenePath(key){const map=activeMap(),names=[];let cursor=key;while(cursor){names.unshift(map[cursor]?.title||'未命名场景');cursor=sceneTree[cursor]?.parent}return names.join(' / ')}
function allSceneKeys(){const result=[];function walk(key){result.push(key);(sceneTree[key]?.children||[]).forEach(walk)}walk('region');return result}
function renderTree(){const map=activeMap(),rows=[];function walk(key,depth){const node=map[key];if(!node)return;rows.push(`<div class="tree-row ${key===editingSceneKey?'active':''}" draggable="${key!=='region'}" data-depth="${Math.min(depth,3)}" data-scene-key="${key}"><span>${sceneTree[key].children.length?'▾':'·'}</span> ${node.title}${key==='desk'?'<span class="cycle">↻</span>':''}</div>`);sceneTree[key].children.forEach(child=>walk(child,depth+1))}walk('region',0);$('#sceneTree').innerHTML=rows.join('');$('.panel-title strong').textContent=state.region;$$('.tree-row[data-scene-key]').forEach(row=>{row.onclick=()=>openSceneEditor(row.dataset.sceneKey);row.ondragstart=e=>{e.dataTransfer.setData('text/plain',row.dataset.sceneKey);row.classList.add('dragging')};row.ondragend=()=>row.classList.remove('dragging');row.ondragover=e=>{e.preventDefault();row.classList.add('drop-target')};row.ondragleave=()=>row.classList.remove('drop-target');row.ondrop=e=>{e.preventDefault();row.classList.remove('drop-target');moveScene(e.dataTransfer.getData('text/plain'),row.dataset.sceneKey)}})}
function moveScene(key,newParent){if(!key||key==='region'||key===newParent)return;const map=activeMap();let cursor=newParent;while(cursor){if(cursor===key)return toast('不能将场景移动到自己的子场景中');cursor=sceneTree[cursor]?.parent}const oldParent=sceneTree[key].parent;sceneTree[oldParent].children=sceneTree[oldParent].children.filter(child=>child!==key);sceneTree[newParent].children.push(key);sceneTree[key].parent=newParent;save(true);renderTree();renderScene();toast(`已将${map[key].title}移动到${map[newParent].title}下`)}
function openSceneEditor(key){editingSceneKey=key;const s=activeMap()[key];$('#editName').textContent=s.title;$('#sceneNameInput').value=s.title;$('#sceneIconInput').value=s.icon||'pin';$('#sceneDescInput').value=s.copy;$('#newScene').textContent=`＋ 在“${s.title}”下新建`;renderTree();renderActions();renderConnections()}
function renderActions(){const opts=activeMap()[editingSceneKey].options.filter(option=>option.kind!=='navigate');$('#actionEditor').innerHTML=opts.map(o=>`<div class="action-card" data-kind="${o.kind}" data-tag="${o.tag||''}" data-nature="${o.timeNature||''}" data-record-mode="${o.recordMode||''}"><input value="${o.name}"><select disabled><option>${o.kind==='睡眠'?'进入睡眠状态':o.timeNature==='positive'?'仅手动同步':'日迹计时'}</option></select><button aria-label="删除">×</button></div>`).join('');$$('.action-card button').forEach(b=>b.onclick=()=>b.parentElement.remove())}
function renderConnections(){const map=activeMap(),links=(map[editingSceneKey].options||[]).filter(option=>option.kind==='navigate');$('#connectionEditor').innerHTML=links.length?links.map(link=>`<div class="connection-row"><span>${link.name}</span><small>→ ${map[link.target]?.title||'已删除场景'}</small><button type="button" data-target="${link.target}" data-name="${link.name}" aria-label="删除联通">×</button></div>`).join(''):'<p class="scene-copy">尚未添加自定义联通。父子通道会自动生成。</p>';$$('.connection-row button').forEach(button=>button.onclick=()=>{const scene=map[editingSceneKey];scene.options=scene.options.filter(option=>!(option.kind==='navigate'&&option.target===button.dataset.target&&option.name===button.dataset.name));save(true);renderConnections();renderScene()})}
$('#addConnection').onclick=()=>{const map=activeMap();$('#connectionTarget').innerHTML=allSceneKeys().filter(key=>key!==editingSceneKey).map(key=>`<option value="${key}">${map[key].title}</option>`).join('');$('#connectionForward').value='';$('#connectionBack').value='';$('#connectionBoth').checked=true;$('#connectionDialog').showModal()};
$('#saveConnection').onclick=()=>{const map=activeMap(),from=editingSceneKey,to=$('#connectionTarget').value,forward=$('#connectionForward').value.trim()||`前往${map[to].title}`,back=$('#connectionBack').value.trim()||`返回${map[from].title}`;map[from].options.push({name:forward,hint:`通往${map[to].title} · 不计时`,kind:'navigate',target:to,timeNature:'passage',recordMode:'none',tag:''});if($('#connectionBoth').checked)map[to].options.push({name:back,hint:`通往${map[from].title} · 不计时`,kind:'navigate',target:from,timeNature:'passage',recordMode:'none',tag:''});save(true);$('#connectionDialog').close();renderConnections();renderScene();toast('场景联通已创建')};
function sceneOptionsForRegion(region){const map=sceneMaps[region],tree=sceneTrees[region],rows=[];function walk(key,depth){if(!map?.[key]||!tree?.[key])return;rows.push(`<option value="${key}">${'　'.repeat(depth)}${map[key].title}</option>`);tree[key].children.forEach(child=>walk(child,depth+1))}walk('region',0);return rows.join('')}
function refreshCopyParents(){$('#copyTargetParent').innerHTML=sceneOptionsForRegion($('#copyTargetRegion').value)}
$('#copySceneBranch').onclick=()=>{if(editingSceneKey==='region')return toast('地区根节点请使用“复制地区”');$('#copySceneHeading').textContent=`复制“${activeMap()[editingSceneKey].title}”分支`;$('#copyTargetRegion').innerHTML=regionNames().map(name=>`<option value="${name}" ${name===state.region?'selected':''}>${name}</option>`).join('');refreshCopyParents();$('#copySceneDialog').showModal()};
$('#copyTargetRegion').onchange=refreshCopyParents;
$('#confirmCopyScene').onclick=()=>{const targetRegion=$('#copyTargetRegion').value,targetParent=$('#copyTargetParent').value;if(!targetRegion||!targetParent)return toast('请选择复制位置');RijiData.createBackup(state,'before-scene-branch-copy');const result=RijiData.copySceneBranch(activeMap(),sceneTree,editingSceneKey,sceneMaps[targetRegion],sceneTrees[targetRegion],targetParent);if(targetRegion===state.region){editingSceneKey=result.rootKey;state.currentScenes[state.region]=result.rootKey}save(true);$('#copySceneDialog').close();renderTree();if(targetRegion===state.region){openSceneEditor(result.rootKey);renderScene()}toast(`分支副本已放入${sceneMaps[targetRegion][targetParent].title}`)};
function renderRegionManager(){const archived=new Set(state.archivedRegions||[]),active=activeRegionNames();$('#activeRegionManager').innerHTML=`<h3>使用中的地区</h3>${active.map(name=>`<div class="region-manager-row"><strong>${name}</strong><button type="button" data-region-action="rename" data-region-name="${name}">重命名</button><button type="button" data-region-action="copy" data-region-name="${name}">复制</button><button type="button" class="danger" data-region-action="archive" data-region-name="${name}">归档</button></div>`).join('')}`;$('#archivedRegionManager').innerHTML=`<h3>已归档</h3>${archived.size?[...archived].map(name=>`<div class="region-manager-row"><strong>${name}</strong><button type="button" data-region-action="restore" data-region-name="${name}">恢复</button><button type="button" class="danger" data-region-action="delete" data-region-name="${name}">删除</button></div>`).join(''):'<p class="region-manager-empty">暂无已归档地区</p>'}`;$$('[data-region-action]').forEach(button=>button.onclick=()=>{if(button.dataset.regionAction==='restore'){RijiData.createBackup(state,'before-region-restore');restoreRegion(button.dataset.regionName);save(true);renderRegionManager();renderRegionOptions();return toast('地区已恢复')}openRegionOperation(button.dataset.regionAction,button.dataset.regionName)})}
function openRegionOperation(mode,name){regionEditMode={mode,name};$('#regionManagerDialog').close();$('#regionNameWrap').classList.toggle('hidden',mode==='archive'||mode==='delete');$('#permanentDeleteRegion').classList.add('hidden');$('#permanentDeleteRegion').dataset.armed='';const labels={rename:'重命名地区',copy:'复制整个地区',archive:'归档地区',delete:'删除已归档地区'};$('#regionEditLabel').textContent=labels[mode];$('#regionEditHeading').textContent=name;$('#regionNameEdit').value=mode==='copy'?`${name} 副本`:name;$('#regionEditMessage').textContent=mode==='archive'?'场景和历史流水都会保留，地区将从日常选择列表中隐藏。':mode==='delete'?'可以继续保留归档，或永久删除该地区及其全部流水。此操作不可撤销。':mode==='copy'?'复制全部场景、行动和联通，不复制历史流水。':'历史流水中的地区名称也会一并更新。';$('#confirmRegionEdit').textContent=mode==='archive'?'归档':mode==='delete'?'保留归档':'确认';if(mode==='delete')$('#permanentDeleteRegion').classList.remove('hidden');$('#regionEditDialog').showModal()}
function renameRegion(oldName,newName){sceneMaps[newName]=sceneMaps[oldName];sceneTrees[newName]=sceneTrees[oldName];delete sceneMaps[oldName];delete sceneTrees[oldName];sceneMaps[newName].region.title=newName;Object.values(sceneMaps[newName]).forEach(scene=>{if(scene.path)scene.path=scene.path.replace(oldName,newName)});state.records.forEach(record=>{if(record.region===oldName)record.region=newName});state.currentScenes[newName]=state.currentScenes[oldName];delete state.currentScenes[oldName];if(state.customScenes?.[oldName]){state.customScenes[newName]=state.customScenes[oldName];delete state.customScenes[oldName]}if(scenes[oldName]){scenes[newName]=scenes[oldName];delete scenes[oldName]}if(state.region===oldName)state.region=newName;sceneTree=sceneTrees[state.region]}
function copyRegion(source,name){sceneMaps[name]=RijiData.clone(sceneMaps[source]);sceneTrees[name]=RijiData.clone(sceneTrees[source]);sceneMaps[name].region.title=name;Object.values(sceneMaps[name]).forEach(scene=>{if(scene.path)scene.path=scene.path.replace(source,name)});state.currentScenes[name]='region'}
function archiveRegion(name){if(activeRegionNames().length<2)return toast('至少需要保留一个使用中的地区');state.archivedRegions=[...new Set([...state.archivedRegions,name])];if(state.region===name){state.region=activeRegionNames().find(region=>region!==name);sceneTree=sceneTrees[state.region];editingSceneKey=state.currentScenes[state.region]||'region';$('#regionSelect').value=state.region}}
function restoreRegion(name){state.archivedRegions=state.archivedRegions.filter(region=>region!==name)}
function deleteRegionPermanently(name){const removed=state.records.filter(record=>record.region===name);state.deletedRecordIds=[...new Set([...state.deletedRecordIds,...removed.map(record=>record.id)])];state.records=state.records.filter(record=>record.region!==name);delete sceneMaps[name];delete sceneTrees[name];delete state.currentScenes[name];delete state.customScenes?.[name];delete scenes[name];state.archivedRegions=state.archivedRegions.filter(region=>region!==name)}
$('#manageRegions').onclick=()=>{renderRegionManager();$('#regionManagerDialog').showModal()};
$('#confirmRegionEdit').onclick=()=>{if(!regionEditMode)return;const {mode,name}=regionEditMode,newName=$('#regionNameEdit').value.trim();if(mode==='delete')return $('#regionEditDialog').close();if((mode==='rename'||mode==='copy')&&!newName)return toast('请输入地区名称');if(mode==='copy'&&sceneMaps[newName])return toast('该地区名称已经存在');if(mode==='rename'&&newName!==name&&sceneMaps[newName])return toast('该地区名称已经存在');if(mode==='archive'&&activeRegionNames().length<2)return toast('至少需要保留一个使用中的地区');RijiData.createBackup(state,`before-region-${mode}`);if(mode==='rename'&&newName!==name)renameRegion(name,newName);if(mode==='copy')copyRegion(name,newName);if(mode==='archive')archiveRegion(name);save(true);$('#regionEditDialog').close();renderRegionOptions();renderTree();openSceneEditor(editingSceneKey);renderScene();renderTimeline();renderDistribution();toast(mode==='archive'?'地区已归档':mode==='copy'?'地区副本已创建':'地区名称已更新')};
$('#permanentDeleteRegion').onclick=()=>{if(!regionEditMode||regionEditMode.mode!=='delete')return;const button=$('#permanentDeleteRegion');if(button.dataset.armed!=='true'){button.dataset.armed='true';button.textContent='再次点击，永久删除';return}RijiData.createBackup(state,'before-region-permanent-delete');deleteRegionPermanently(regionEditMode.name);save(true);$('#regionEditDialog').close();renderRegionOptions();toast('地区及其流水已永久删除')};
$('#regionSelect').value=state.region;$('#regionConfirm').onclick=switchRegion;$('#regionToggle').onclick=toggleRegionOptions;$('#regionSelect').onfocus=openRegionOptions;$('#regionSelect').oninput=()=>{const query=$('#regionSelect').value.trim().toLocaleLowerCase();$$('#regionOptions [data-region]').forEach(button=>button.classList.toggle('hidden',!button.dataset.region.toLocaleLowerCase().includes(query)))};$('#regionSelect').onkeydown=e=>{if(e.key==='Enter')switchRegion();if(e.key==='Escape')closeRegionOptions()};renderRegionOptions();
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.region-combobox'))closeRegionOptions()});
$('#addRegion').onclick=()=>{$('#regionSelect').value='';$('#regionSelect').placeholder='输入新地区名称';openRegionOptions();$('#regionSelect').focus();toast('输入名称后按回车创建地区')};
$('#timelineDate').value=isoToday;function shiftDay(n){const d=new Date($('#timelineDate').value+'T12:00:00');d.setDate(d.getDate()+n);$('#timelineDate').value=d.toISOString().slice(0,10);renderTimeline()}$('#prevDay').onclick=()=>shiftDay(-1);$('#nextDay').onclick=()=>shiftDay(1);$('#timelineDate').onchange=renderTimeline;
$('#addRecord').onclick=()=>openSyncDialog();
$('#saveScene').onclick=()=>{const map=activeMap(),s=map[editingSceneKey],oldTitle=s.title,links=s.options.filter(option=>option.kind==='navigate');s.title=$('#sceneNameInput').value.trim()||s.title;s.icon=$('#sceneIconInput').value;s.copy=$('#sceneDescInput').value.trim();const actions=$$('.action-card').map(card=>{const name=card.querySelector('input').value.trim()||'未命名行动',kind=card.dataset.kind,tag=card.dataset.tag||'',timeNature=card.dataset.nature||(kind==='娱乐'?'neutral':'positive'),recordMode=card.dataset.recordMode||(timeNature==='positive'?'external':'internal');if(kind==='睡眠')return {name,hint:'开始睡眠记录',kind:'睡眠',tag:'',timeNature:'sleep',recordMode:'none'};return {name,hint:`${tag||kind} · 可计时`,kind,tag,timeNature,recordMode}});s.options=[...actions,...links];if(oldTitle!==s.title)Object.values(map).forEach(scene=>(scene.options||[]).forEach(option=>{if(option.target===editingSceneKey){option.hint=`通往${s.title} · 不计时`;if(option.name===`前往${oldTitle}`||option.name==='前往新场景')option.name=`前往${s.title}`}}));$('#editName').textContent=s.title;save(true);renderTree();renderScene();renderConnections();toast('场景修改已保存')};
$('#addAction').onclick=()=>{const el=document.createElement('div');el.className='action-card';el.dataset.kind='生活';el.dataset.nature='positive';el.dataset.recordMode='external';el.dataset.tag='';el.innerHTML='<input placeholder="行动名称"><select disabled><option>仅手动同步</option></select><button aria-label="删除">×</button>';el.querySelector('button').onclick=()=>el.remove();$('#actionEditor').append(el)};
$('#newScene').onclick=()=>{const map=activeMap(),parent=editingSceneKey||'region',key=`scene_${Date.now()}`;sceneTree[key]={parent,children:[]};sceneTree[parent].children.push(key);map[key]={title:'新场景',icon:'pin',path:'',copy:'这是一个新场景。请填写它的描述，并添加行动或通道。',options:[{name:`返回${map[parent].title}`,hint:`通往${map[parent].title} · 不计时`,kind:'navigate',target:parent,timeNature:'passage',recordMode:'none',tag:''}]};map[parent].options.push({name:'前往新场景',hint:'通往新场景 · 不计时',kind:'navigate',target:key,timeNature:'passage',recordMode:'none',tag:''});editingSceneKey=key;save(true);renderTree();openSceneEditor(key);toast(`已在${map[parent].title}下创建场景`)};
$('#deleteScene').onclick=()=>{if(editingSceneKey==='region')return toast('地区根场景不能删除');$('#deleteSceneName').textContent=`删除“${activeMap()[editingSceneKey].title}”`;$('#deleteSceneDialog').showModal()};
$('#confirmDeleteScene').onclick=()=>{const map=activeMap(),key=editingSceneKey,parent=sceneTree[key].parent,mode=$('#deleteChildrenMode').value,removed=[];function collect(node){removed.push(node);sceneTree[node].children.forEach(collect)}if(mode==='all')collect(key);else{removed.push(key);sceneTree[key].children.forEach(child=>{sceneTree[child].parent=parent;sceneTree[parent].children.push(child)})}sceneTree[parent].children=sceneTree[parent].children.filter(child=>child!==key);removed.forEach(node=>{delete sceneTree[node];delete map[node]});Object.values(map).forEach(scene=>{scene.options=(scene.options||[]).filter(option=>!removed.includes(option.target))});const current=state.currentScenes?.[state.region];if(removed.includes(current))state.currentScenes[state.region]=parent;editingSceneKey=parent;save(true);$('#deleteSceneDialog').close();openSceneEditor(parent);renderScene();toast('场景已删除，历史流水已保留')};
let pendingImportData=null;
function downloadFile(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderDataManager(){const backups=RijiData.backups(),lastDate=state.records.map(record=>record.date).sort().at(-1)||'暂无',reasonLabels={auto:'自动备份',manual:'手动备份','before-cloud-merge':'云端合并前','before-scene-conflict-resolution':'场景冲突处理前','before-timer-conflict-resolution':'计时冲突处理前','before-overlap-resolution':'重叠处理前','before-import':'导入前','before-restore':'恢复前'};$('#dataStats').innerHTML=`<div><span>数据版本</span><strong>v${RijiData.SCHEMA_VERSION}</strong></div><div><span>流水记录</span><strong>${state.records.length}</strong></div><div><span>最后记录</span><strong>${lastDate}</strong></div>`;$('#backupList').innerHTML=backups.length?backups.map(item=>`<div class="backup-row"><div><strong>${new Date(item.createdAt).toLocaleString('zh-CN')}</strong><small>${reasonLabels[item.reason]||'本地备份'} · ${item.recordCount} 条记录</small></div><button type="button" data-backup-id="${item.id}">恢复</button></div>`).join(''):'<p class="scene-copy">还没有本地备份。</p>';$$('[data-backup-id]').forEach(button=>button.onclick=()=>{RijiData.createBackup(state,'before-restore');RijiData.restore(button.dataset.backupId);location.reload()})}
function resolveOverlap(action,firstId,secondId){const first=state.records.find(record=>String(record.id)===String(firstId)),second=state.records.find(record=>String(record.id)===String(secondId));if(!first||!second||first.date!==second.date)return toast('该冲突需要手动编辑');RijiData.createBackup(state,'before-overlap-resolution');if(action==='trim'&&minutes(second.start)>minutes(first.start))first.end=second.start;else if(action==='shift'&&minutes(first.end)<minutes(second.end))second.start=first.end;else return toast('无法自动处理该包含关系，请手动编辑');const changed=action==='trim'?first:second;changed.updatedAt=clockNow().toISOString();save();renderRecordConflictAudit();renderTimeline();renderDistribution();toast(action==='trim'?'已截断前一条流水':'已后移后一条流水')}
function renderRecordConflictAudit(){const conflicts=RijiData.findRecordOverlaps(state.records);$('#recordConflictCount').textContent=String(conflicts.length);$('#recordConflictList').innerHTML=conflicts.length?conflicts.map(item=>{const sameDay=item.first.date===item.second.date,canTrim=sameDay&&minutes(item.second.start)>minutes(item.first.start),canShift=sameDay&&minutes(item.first.end)<minutes(item.second.end);return `<div class="record-conflict-row"><button type="button" data-conflict-record="${item.first.id}"><strong>${item.first.name}</strong><small>${item.first.date} · ${item.first.start}–${item.first.end} · ${item.region}</small></button><div class="conflict-actions"><span>重叠 ${item.minutes} 分钟</span>${canTrim?`<button type="button" data-overlap-action="trim" data-first="${item.first.id}" data-second="${item.second.id}">截断前项</button>`:''}${canShift?`<button type="button" data-overlap-action="shift" data-first="${item.first.id}" data-second="${item.second.id}">后移后项</button>`:''}</div><button type="button" data-conflict-record="${item.second.id}"><strong>${item.second.name}</strong><small>${item.second.date} · ${item.second.start}–${item.second.end} · ${item.region}</small></button></div>`}).join(''):'<p class="scene-copy">没有发现重叠流水。</p>';$$('[data-conflict-record]').forEach(button=>button.onclick=()=>{$('#dataDialog').close();openRecordEditor(button.dataset.conflictRecord)});$$('[data-overlap-action]').forEach(button=>button.onclick=()=>resolveOverlap(button.dataset.overlapAction,button.dataset.first,button.dataset.second))}
function renderCloudAccount(){const session=RijiCloud.session(),signedIn=Boolean(session?.access_token),hasConflict=Boolean(state.sync?.sceneConflict),hasTimerConflict=Boolean(state.sync?.timerConflict);$('#cloudLogin').classList.toggle('hidden',signedIn);$('#cloudAccount').classList.toggle('hidden',!signedIn);$('#syncNow').classList.toggle('hidden',!signedIn);$('#sceneConflict').classList.toggle('hidden',!signedIn||!hasConflict);$('#timerConflict').classList.toggle('hidden',!signedIn||!hasTimerConflict);$('#cloudUser').textContent=session?.user?.email||'';$('#cloudSummary').textContent=signedIn?(hasConflict?'需要选择要保留的场景版本':hasTimerConflict?'需要处理计时会话冲突':state.sync?.lastSyncedAt?`上次同步：${new Date(state.sync.lastSyncedAt).toLocaleString('zh-CN')}`:'已登录，尚未完成首次同步'):'尚未连接云端账户'}
async function resolveSceneConflict(useCloud){const conflict=state.sync?.sceneConflict;if(!conflict)return;RijiData.createBackup(state,'before-scene-conflict-resolution');if(useCloud)Object.assign(state,RijiData.clone(conflict.remoteConfig));state.sync.sceneRevision=Math.max(conflict.localRevision||0,conflict.remoteRevision||0)+1;state.sync.sceneConflict=null;RijiData.save(state);setCloudMessage('正在保存场景选择…','pending');try{await RijiCloud.sync(state);toast(useCloud?'已采用云端场景版本':'已保留此设备的场景版本');setTimeout(()=>location.reload(),500)}catch(error){setCloudMessage(`同步失败：${error.message}`,'error');toast('选择已保存在本机，联网后请再次同步')}}
async function resolveTimerConflict(mode){const conflict=state.sync?.timerConflict;if(!conflict)return;RijiData.createBackup(state,'before-timer-conflict-resolution');if(mode==='both'&&conflict.remoteTimer)recordTimer(RijiData.clone(conflict.remoteTimer),Date.parse(conflict.detectedAt)||Date.now());if(mode==='cloud')state.activeTimer=RijiData.clone(conflict.remoteTimer);state.sync.timerRevision=Math.max(conflict.localRevision||0,conflict.remoteRevision||0)+1;state.sync.timerConflict=null;RijiData.save(state);setCloudMessage('正在保存计时选择…','pending');try{await RijiCloud.sync(state);toast(mode==='cloud'?'已采用云端计时会话':mode==='both'?'已保存云端片段并保留本机会话':'已保留本机会话');setTimeout(()=>location.reload(),500)}catch(error){setCloudMessage(`同步失败：${error.message}`,'error');toast('选择已保存在本机，联网后请再次同步')}}
function setCloudMessage(message,stateName=''){$('#cloudSummary').textContent=message;$('#cloudSummary').dataset.state=stateName}
function cloudErrorMessage(error,prefix){if(error.code==='over_email_send_rate_limit'||/email rate limit/i.test(error.message))return'确认邮件发送额度已用完，请先检查收件箱和垃圾邮件，稍后再试';if(error.status===429)return'请求过于频繁，请等待几分钟后再试';return`${prefix}：${error.message}`}
async function runCloudSync(){setCloudMessage('正在与云端合并数据…','pending');try{const result=await RijiCloud.sync(state);if(result.signedOut){setCloudMessage('请先登录云同步','error');return toast('请先登录云同步')}renderCloudAccount();if(result.changed){setCloudMessage('已合并其他设备的数据','success');toast('已合并其他设备的数据');setTimeout(()=>location.reload(),700)}else{setCloudMessage('云端数据已同步','success');toast('云端数据已同步')}}catch(error){const message=error.status===404?'云端数据表尚未初始化':`同步失败：${error.message}`;setCloudMessage(message,'error');toast(message)}}
async function cloudAuth(mode){const email=$('#cloudEmail').value.trim(),password=$('#cloudPassword').value,buttons=[$('#cloudSignin'),$('#cloudSignup')];if(!email||password.length<8){setCloudMessage('请输入有效邮箱和至少 8 位密码','error');return toast('请输入邮箱和至少 8 位密码')}buttons.forEach(button=>button.disabled=true);setCloudMessage(mode==='signup'?'正在创建账户…':'正在登录…','pending');try{const result=await RijiCloud.authenticate(email,password,mode);if(result.needsConfirmation){setCloudMessage(`确认邮件已发送至 ${email}，请点击邮件中的链接后再登录`,'success');return toast('账户已创建，请检查确认邮件')}renderCloudAccount();await runCloudSync()}catch(error){const message=cloudErrorMessage(error,mode==='signup'?'注册失败':'登录失败');setCloudMessage(message,'error');toast(message)}finally{buttons.forEach(button=>button.disabled=false)}}
$('#cloudSignin').onclick=()=>cloudAuth('signin');$('#cloudSignup').onclick=()=>cloudAuth('signup');$('#syncNow').onclick=runCloudSync;$('#cloudSignout').onclick=()=>{RijiCloud.signOut();renderCloudAccount();toast('已退出云同步，本地数据仍保留')};
$('#keepLocalScenes').onclick=()=>resolveSceneConflict(false);$('#useCloudScenes').onclick=()=>resolveSceneConflict(true);
$('#keepLocalTimer').onclick=()=>resolveTimerConflict('local');$('#saveBothTimers').onclick=()=>resolveTimerConflict('both');$('#useCloudTimer').onclick=()=>resolveTimerConflict('cloud');
window.addEventListener('riji-cloud-status',event=>{const {status,message}=event.detail,$state=$('#syncState');$state.dataset.status=status;$state.querySelector('b').textContent=message});
$('#openDataManager').onclick=()=>{pendingImportData=null;$('#importPreview').classList.add('hidden');renderDataManager();renderRecordConflictAudit();renderCloudAccount();renderClockAudit();$('#dataDialog').showModal()};
$('#exportJson').onclick=()=>{const stamp=new Date().toISOString().slice(0,10);downloadFile(`日迹备份-${stamp}.json`,JSON.stringify(RijiData.envelope(state),null,2),'application/json;charset=utf-8');toast('JSON 备份已导出')};
$('#exportCsv').onclick=()=>{const fields=['日期','开始','结束','行动','时间性质','Tag','地区','场景','来源','睡眠质量'],escape=value=>`"${String(value??'').replaceAll('"','""')}"`,rows=state.records.map(record=>[record.date,record.start,record.end,record.name,record.timeNature,record.tag,record.region||'上海',record.path,record.source,record.sleepQuality].map(escape).join(','));downloadFile(`日迹流水-${new Date().toISOString().slice(0,10)}.csv`,`\ufeff${fields.join(',')}\r\n${rows.join('\r\n')}`,'text/csv;charset=utf-8');toast('CSV 流水已导出')};
$('#createBackup').onclick=()=>{RijiData.createBackup(state,'manual');renderDataManager();toast('本地备份已创建')};
$('#chooseImport').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{pendingImportData=RijiData.parseImport(await file.text());$('#importSummary').textContent=`${file.name} · 数据版本 v${pendingImportData.schemaVersion} · ${pendingImportData.records.length} 条流水。合并会保留两边记录并检测场景冲突；覆盖会替换当前内容。两种方式都会先备份。`;$('#importPreview').classList.remove('hidden')}catch(error){pendingImportData=null;toast(`无法导入：${error.message}`)}event.target.value=''};
$('#mergeImport').onclick=()=>{if(!pendingImportData)return;RijiData.createBackup(state,'before-import');RijiData.save(RijiData.merge(state,pendingImportData));location.reload()};
$('#applyImport').onclick=()=>{if(!pendingImportData)return;RijiData.createBackup(state,'before-import');pendingImportData.sync={...(pendingImportData.sync||{}),sceneRevision:(state.sync?.sceneRevision||0)+1,timerRevision:(state.sync?.timerRevision||0)+1,sceneConflict:null,timerConflict:null};RijiData.save(pendingImportData);location.reload()};
$('#resetDemo').onclick=()=>{RijiData.createBackup(state,'before-reset');localStorage.removeItem('riji-state');location.reload()};
function renderClock(){const now=clockNow(),clock=RijiCloud.clock(),minutesOff=Math.round(Math.abs(clock.offsetMs)/60000),warning=minutesOff>=2,compact=window.innerWidth<=900,formatted=new Intl.DateTimeFormat('zh-CN',compact?{timeStyle:'short',hour12:false}:{dateStyle:'medium',timeStyle:'medium',hour12:false}).format(now);$('#clock').textContent=`${formatted}${warning?' · 偏差警告':''}`;$('#clock').dataset.state=warning?'warning':'calibrated';$('#clock').title=clock.checkedAt?`已按云端校准${warning?`，设备时间偏差约 ${minutesOff} 分钟`:''} · ${new Date(clock.checkedAt).toLocaleString('zh-CN')}`:'尚未连接云端校准时间'}renderClock();setInterval(renderClock,1000);window.addEventListener('resize',renderClock);window.addEventListener('riji-clock-calibrated',renderClock);
function renderClockAudit(){const clock=RijiCloud.clock(),minutesOff=Math.round(Math.abs(clock.offsetMs)/60000),warning=minutesOff>=2,summary=$('#clockAuditSummary');summary.dataset.state=warning?'warning':'ready';summary.textContent=clock.checkedAt?`上次校准：${new Date(clock.checkedAt).toLocaleString('zh-CN')} · ${warning?`设备时间偏差约 ${minutesOff} 分钟`:'设备时间正常'}`:'尚未成功读取服务器时间'}
$('#recalibrateClock').onclick=async()=>{const button=$('#recalibrateClock');button.disabled=true;button.textContent='校准中…';await RijiCloud.calibrate();renderClock();renderClockAudit();button.disabled=false;button.textContent='重新校准';toast(RijiCloud.clock().checkedAt?'时间校准完成':'未能读取服务器时间，请稍后重试')};window.addEventListener('riji-clock-calibrated',renderClockAudit);renderClockAudit();
function renderMonthOptions(){const current=clockNow(),currentMonth=`${current.getFullYear()}-${String(current.getMonth()+1).padStart(2,'0')}`,months=[...new Set([currentMonth,...state.records.map(record=>record.date.slice(0,7))])].sort().reverse(),selected=months.includes($('#monthSelect').value)?$('#monthSelect').value:currentMonth;$('#monthSelect').innerHTML=months.map(month=>{const [year,number]=month.split('-');return `<option value="${month}">${year}年${Number(number)}月</option>`}).join('');$('#monthSelect').value=selected}renderMonthOptions();$$('.segmented button').forEach(button=>button.onclick=()=>{distributionMode=button.textContent.includes('自然')?'natural':'recorded';$$('.segmented button').forEach(item=>item.classList.toggle('active',item===button));$('.distribution .section-title p').textContent=distributionMode==='natural'?'占本月自然时间的比例':'占已记录活动时间的比例';renderDistribution()});$('#monthSelect').onchange=renderDistribution;
editingSceneKey=state.currentScenes?.[state.region]||(activeMap().desk?'desk':'home');renderScene();renderTimeline();renderDistribution();openSceneEditor(editingSceneKey);
renderCloudAccount();RijiCloud.calibrate();if(RijiCloud.session())runCloudSync();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
